name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn --version
      - run: mkdir artifacto && touch artifacto/file.txt
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacto
          path: artifacto
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacto
          path: artifacto
      - run: cd artifacto
      - run: ls


