name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: "{{ secrets.AWS_DEPLOY_ROLE_ARN }}"
        role-session-name: gitHubActions
    - name : Test Credentials
      run: aws s3 ls
